version: "3.8"

services:
  app:
    restart: always
    build: .
    ports:
      - "80:8000"
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_DATABASE=jobby_resume
      - DB_HOST=34.226.154.58
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=3306
      - DB_NAME=${DB_NAME}
      - MYSQL_SSL_MODE=DISABLED
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=jobby_resume
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
