"""Default Params

Revision ID: 2047c39ea9f2
Revises: eaf938b47074
Create Date: 2025-02-24 21:19:58.805788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2047c39ea9f2'
down_revision: Union[str, None] = 'eaf938b47074'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_resumes', sa.Column('tags', sa.JSON(), nullable=True))
    op.alter_column('candidate_resumes', 'jobby_rating',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=4, asdecimal=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidate_resumes', 'jobby_rating',
               existing_type=sa.Float(precision=4, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_column('candidate_resumes', 'tags')
    # ### end Alembic commands ###
